// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bucgleerydlfsfrqxwwh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ1Y2dsZWVyeWRsZnNmcnF4d3doIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDYzODUyMjMsImV4cCI6MjA2MTk2MTIyM30.4L-mCVzKNyVCumWFYGsqjTBymfo0FGJYNdCngNmwvms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);